DHUHUR_DUAA_VIDEO_URL = "./assets/DUAA_ALSHAARAWY.mp4"
DHUHUR_DUAA_VIDEO_DURATION = 70
MAGHRIB_ALSHAARAWY_DUAA_VIDEO_URL = "./assets/DUAA_ALSHAARAWY_AFTER_MAGHREB.mp4"
MAGHRIB_ALSHAARAWY_DUAA_VIDEO_DURATION = 35
MAGHRIB_ALSHAARAWY_DUAA_AUDIO_URL = "https://archive.org/download/sharawy_doaa_24/sharawy_doaa_24.mp3"
MAGHRIB_ALSHAARAWY_DUAA_AUDIO_DURATION = 68

DUAAS = {
    "DHUHUR_DUAA_VIDEO": {
        "URL": DHUHUR_DUAA_VIDEO_URL,
        "DURATION": DHUHUR_DUAA_VIDEO_DURATION
    },
    "MAGHRIB_ALSHAARAWY_DUAA_VIDEO": {
        "URL": MAGHRIB_ALSHAARAWY_DUAA_VIDEO_URL,
        "DURATION": MAGHRIB_ALSHAARAWY_DUAA_VIDEO_DURATION
    },
    "MAGHRIB_ALSHAARAWY_DUAA_AUDIO": {
        "URL": MAGHRIB_ALSHAARAWY_DUAA_AUDIO_URL,
        "DURATION": MAGHRIB_ALSHAARAWY_DUAA_AUDIO_DURATION
    }
}